version: '3.7'
services:

  axonserver:
    image: axoniq/axonserver:4.4.5
    container_name: axonserver
    hostname: axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    environment:
      - AXONSERVER_HOSTNAME=axonserver

  axon-demo:
    container_name: axon-demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AXON_SERVER=axonserver
    command: >
      dockerize
      -wait tcp://axonserver:8124 -timeout 60s
      java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  #    volumes:
  #      - ./axon-multi-person/target/axon-multi-person-1.0-SNAPSHOT.jar:/app.jar

 
